export const elementsWithInput = ['input', 'textarea', 'select']
export const elementsWithLink = ['a']
export const elementsWithNavigation = ['input', 'button']
export const elemensWithNavigationInputType = ['submit']
export const inputTypesThatNeedOptions = ['select']
